[tools]
bazel = "latest"
cmake = "3.31.10"
flutter = "3.27.4-stable"
fzf = "0.67.0"
go = "1.25.5"
java = "{% if get_env(name='WSL_DISTRO_NAME', default='') != '' %}corretto-8.472.08.1{% else %}openjdk-21.0.2{% endif %}"
kotlin = "latest"
lua-language-server = "latest"
minikube = "latest"
node = "20.19.6"
proto = "latest"
python = "3.12.12"
rust = "latest"
tmux = "latest"
uv = "latest"
yt-dlp = "latest"
zig = "latest"
"cargo:bat" = "latest"
"cargo:du-dust" = "latest"
"cargo:gitlogue" = "latest"
"cargo:lsd" = "latest"
"cargo:ripgrep" = "latest"
"cargo:fd-find" = "latest"
"cargo:https://github.com/kiddos/basecode-lsp" = "latest"
"cargo:neocmakelsp" = "latest"
"cargo:protols" = "latest"
"cargo:zoxide" = "latest"
"cargo:yazi-build" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:serie" = "latest"
"cargo:trippy" = "latest"
"github:espressif/idf-im-ui" = "latest"
"npm:prettier" = "latest"
"npm:bash-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:cssmodules-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:corepack" = "latest"
"npm:typescript" = "latest"
"npm:pm2" = "latest"
"cargo:navi" = "latest"

[plugins]
proto = "https://github.com/kiddos/mise-proto"

[env]
_.file = ["~/.env"]
EDITOR = "nvim"
CXX = "clang++"
CC = "clang"
