[tools]
clang = "17.0.6"
clangd = "17.0.6"
cmake = "3.31.10"
flutter = "3.27.4-stable"
fzf = "0.67.0"
go = "1.25.5"
java = "openjdk-21.0.2"
kotlin = "latest"
node = "20.19.6"
protoc = "33.2"
python = "3.13.11"
rust = "stable"
zig = "latest"
